fix : Semantic 환경변수 등록

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -53,7 +53,11 @@ jobs:
             }
           }' > package.json
           VERSION=$(npx semantic-release --no-ci | grep "Published" | awk '{print $2}')
-          echo "SEMANTIC_VERSION=$VERSION" >> $GITHUB_ENV
+          if [ ! -z "$VERSION" ]; then
+            echo "SEMANTIC_VERSION=$VERSION" >> $GITHUB_ENV
+          else
+            echo "Error: SEMANTIC_VERSION not extracted" && exit 1
+          fi
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
